export enum CarManufacturer {
  Toyota = 'Toyota',
  Honda = 'Honda',
  Ford = 'Ford',
  Chevrolet = 'Chevrolet',
  Volkswagen = 'Volkswagen',
  BMW = 'BMW',
  Mercedes = 'Mercedes',
  Audi = 'Audi',
  Nissan = 'Nissan',
  Hyundai = 'Hyundai',
  Kia = 'Kia',
  Mazda = 'Mazda',
  Subaru = 'Subaru',
  Tesla = 'Tesla',
  Renault = 'Renault',
  Peugeot = 'Peugeot',
  Skoda = 'Skoda',
  Volvo = 'Volvo',
  Porsche = 'Porsche',
  Jeep = 'Jeep',
}
